enum SETTING_TYPE {
  WITHDRAWAL = 'WITHDRAWAL',
  KEYSTONE = 'KEYSTONE',
  WEBHOOK = 'WEBHOOK',
  NOTIFICATION = 'NOTIFICATION',
  SECURITY = 'SECURITY',
  TWOFACTOR = 'TWOFACTOR',
  CASHIER = 'CASHIER',
  TRANSACTION = 'TRANSACTION',
}

export { SETTING_TYPE };
