export enum TRANSACTION_STATUS {
  NEW = 'NEW',
  DONE = 'DONE',
  EXPIRED = 'EXPIRED',
}

export const TRANSACTION_STATUS_TEXT = {
  [TRANSACTION_STATUS.NEW]: '未完成',
  [TRANSACTION_STATUS.DONE]: '已完成',
  [TRANSACTION_STATUS.EXPIRED]: '已过期',
};
