export enum WITHDRAWAL_TYPE {
  MANUAL = 'MANUAL',
  API = 'API',
  AUTO = 'AUTO',
}

export const WITHDRAWAL_TYPE_TEXT = {
  [WITHDRAWAL_TYPE.AUTO]: '自动提现',
  [WITHDRAWAL_TYPE.API]: '接口提现',
  [WITHDRAWAL_TYPE.MANUAL]: '手动提现',
};

export enum WITHDRAWAL_STATUS {
  NEW = 'NEW',
  DONE = 'DONE',
  REJECTED = 'REJECTED',
}

export const WITHDRAWAL_STATUS_TEXT = {
  [WITHDRAWAL_STATUS.NEW]: '处理中',
  [WITHDRAWAL_STATUS.DONE]: '已完成',
  [WITHDRAWAL_STATUS.REJECTED]: '已驳回',
};
